Ported VisionOn command (originally ShooterAim)
usfirst-frc-2135/robot2022 pull request #165
Opened 2022-08-27 21:14 UTC by amull23

2022-08-28 00:54 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/VisionOn.java
> +import javax.lang.model.util.ElementScanner6;
Where did this import come from? I don't see this class being used (ElementScanner6).

2022-08-28 00:57 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/VisionOn.java
> +  {
This is a robotcontainer reference like this:
RobotContainer.getInstance( ).m_vision.methodInVisionSubsystemToCall();

2022-08-28 00:57 UTC, jmullins16 requested changes
A couple of small items to fix.

2022-08-29 01:32 UTC, jmullins16 approved these changes
Looks good now!

2022-08-30 01:00 UTC, zaraansari17 reviewed
looks good!

2022-08-30 01:01 UTC, hpark-24 approved these changes
Looks good!

2022-08-30 03:40 UTC, jmullins16 approved these changes
Looks good now.

2022-08-30 03:40 UTC, merged