Porting Drivetrain to Java
usfirst-frc-2135/robot2022 pull request #167
Opened 2022-08-27 22:54 UTC by hpark-24

2022-08-28 00:43 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/RobotContainer.java
> +    SmartDashboard.putData("DriveMotorTest", new DriveMotorTest(true, m_drivetrain));
Let's swap the parameter order here to have the subsystem first. This matches what we were trying to do in C++ for consistency.

2022-08-28 00:46 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/subsystems/Drivetrain.java
> +import edu.wpi.first.math.trajectory.Trajectory.State;
Do an "organize imports" using CMD and . to get these to automatically alphabetize.

2022-08-28 00:48 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/subsystems/Drivetrain.java
> +  public double nativeUnitsToMPS(double velLeftCurrent)
Since this method works on any velocity (right or left wheel speeds), let'c change the parameter name back to "nativeUnitsVelocity".

2022-08-28 00:50 UTC, jmullins16 requested changes
Overall, this is really close. I'll do an A/B comparison with the C++ later, but I think you've done a great job with the initial port of the code. Fix up the few comments I had so we can get this merged and available for everyone. I'm looking forward to trying this out in simulation on path following!

2022-08-30 01:04 UTC, amull23 approved these changes
looks good!

2022-08-30 03:33 UTC, jmullins16 approved these changes
Looks good now. Let's get it merged.

2022-08-30 03:38 UTC, merged