Porting ClimberCalibrate, ClimberRun, ClimberSetGatehook, ClimberTimerOverride to Java
usfirst-frc-2135/robot2022 pull request #170
Opened 2022-08-31 03:04 UTC by hpark-24

2022-09-01 23:06 UTC, amull23 approved these changes
looks good!

2022-09-03 20:57 UTC, jmullins16 requested changes
Looks really good. Just a couple of small changes, and I'd like to get this merged soon.

2022-09-03 20:57 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/ClimberSetGatehook.java
> +  public ClimberSetGatehook(boolean climberSetGateHook)
An improvement for readability in variable naming here. When ClimberSetGateHook() is being called, the caller is requesting that the gate hook be put in one of two states--open or closed. Naming the boolean parameter something like "gateHookClosed" and passing in true or false would be easier for the reader to understand. And change the m_ variable to match it.

2022-09-03 20:57 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/ClimberTimerOverride.java
> +  public ClimberTimerOverride(Climber climber)
We will be modifying all of our "simple" commands to pass (inject) all subsystems in as parameters. So in addition to the Climber subsystem, passing the second parameter as "XboxController gamepad" would be more direct than using RobotContainer.getInstance(). Try to add this second parameter and see if you can simplify the references to the operator controller.

2022-09-09 23:12 UTC, jmullins16 approved these changes
Looks good now! Ready to merge.

2022-09-09 23:12 UTC, merged