Porting Climber0Stow and Fixing ClimberMoveToHeight + RobotContainer
usfirst-frc-2135/robot2022 pull request #178
Opened 2022-09-10 21:09 UTC by hpark-24

2022-09-11 16:32 UTC, jmullins16 requested changes

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber5RotateIntoL3.java
> +      new ClimberSetGatehook(climber, false)
Minor detail, but I think that ClimberSetGateHook should have the same indent level as the others, since it's included in that ParallelDeadlineGroup.

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber7ClimbToL4.java
> +      new ClimberSetGatehook(climber, false)
Same comment as previous. All of the commands enclosed within the ParallelDeadlineGroup should have the same indent level.

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber8SettleToL4.java
> +        new ClimberSetGatehook(climber, false)),
ClimberSetGateHook gets indented, and notice the extra parens on this line. That means the three previous commands are in the first ParallelDeadlineGroup and should have the same indent level. The rest of the commands in here are fine.

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/DriveLimelightShoot.java
> +        new ParallelCommandGroup(new DriveLimelight(drivetrain, vision, false),
Need to format this one still.

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber1Deploy.java
> +    setName("ClimberDeploy");
Change setName to "Climber1Deploy" like the constuctor/filename.

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber3RotateToL3.java
> +    setName("ClimberRotateToL3");
Change setName to Climber3RotateToL3.

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber5RotateIntoL3.java
> +    setName("ClimberRotateIntoL3");
Change setName to Climber5RotateIntoL3

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber6ClimbToL3.java
> +    setName("ClimberClimbToL3");
Change setName to Climber6ClimbToL3

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber7ClimbToL4.java
> +    setName("ClimberClimbToL4");
Change setName to Climber7ClimbToL4

2022-09-11 16:32 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber8SettleToL4.java
> +    setName("ClimberSettleToL4");
Change setName to Climber8SettleToL4

2022-09-11 20:36 UTC, amull23 reviewed
I think the commands on line 38 in DriveLLShoot are not fully broken apart.  Are we okay with condensing the commands or do we want to have one command per line?

2022-09-12 03:43 UTC, jmullins16 requested changes
Looks like you've covered everything except the closing parens which we'd like to have on its own line to terminate parallel or sequential commands. But everything else looks great.

2022-09-12 03:43 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/Climber0Stow.java
> +          new ClimberMoveToHeight(climber, Height.STOW_HEIGHT)),
For consistency with other commands, let's put the closing (second) paren on this line on its own line. Kind of like closing brackets.

2022-09-13 03:02 UTC, jmullins16 commented
Looks great now!

2022-09-13 03:02 UTC, merged