Ported ScoringAction Low and Upper Hub
usfirst-frc-2135/robot2022 pull request #179
Opened 2022-09-11 20:26 UTC by amull23

2022-09-11 21:02 UTC, jmullins16 requested changes
Just that minor change, then I'll approve and it's all good.

2022-09-11 21:02 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/ScoringActionHighHub.java
> +        new ShooterRun(shooter, Mode.SHOOTER_UPPERHUB)),
Let's use the style you have below. Swing the second parens on line 34 around and put it on its own line. Everything else looks good. You'll see the same issue in both LowHub and HighHub.

2022-09-11 21:05 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/commands/ScoringActionHighHub.java
> +        new ShooterRun(shooter, Mode.SHOOTER_UPPERHUB)),
Except I see both using HighHub while one should be using constants and name for LowHub.

2022-09-12 03:30 UTC, jmullins16 commented
Looks like you haven't merged from main yet, either.

2022-09-13 00:05 UTC, zaraansari17 approved these changes
Looks good

2022-09-13 06:07 UTC, jmullins16 approved these changes
Looks correct now!

2022-09-13 06:08 UTC, merged