Redefined m_targetValid and shorted SmartDashBoard puts at intitializitation
usfirst-frc-2135/robot2022 pull request #197
Opened 2022-09-30 04:08 UTC by reevar24

2022-09-30 06:24 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/subsystems/Vision.java
> +      if (m_table.getEntry("tv").getDouble(0.0) > 0)
Let's do this on a single line. We are assigning the variable m_targetValid to be either true or false based on a condition. So

m_targetValid = (m_table.getEntry("tv").getDouble(0.0) > 0);

The parentheses around the comparison will evaluate to "true" or "false" and then be assigned to the variable. Just like if that comparison was used for an "if" statement.

2022-09-30 06:25 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/RobotContainer.java
> +    // SmartDashboard.putData("DriveMotorTest", new DriveMotorTest(m_drivetrain, true));
Leave DriveMotorTest uncommented, because it can be used for tuning the drivetrain and does not exist on any buttons.

2022-09-30 06:27 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/RobotContainer.java
> +    // SmartDashboard.putData("DriveMotorTest", new DriveQuickturn(m_drivetrain));
Looks like the typo for the (now commented out) DriveQuickturn still needs to be fixed and wasn't in the last PR.

2022-09-30 06:28 UTC, jmullins16 commented on Offseason2022/src/main/java/frc/robot/RobotContainer.java
> +    // SmartDashboard.putData("Climber0Stow",
Let's leave climber deploy and climber stow commands uncommented so they can be run in simulation easily.

2022-09-30 06:29 UTC, jmullins16 requested changes
Minor changes in comments. List of commented out commands looks pretty close, and I just recommended leaving a few more uncommented.

2022-10-01 20:17 UTC, amull23 approved these changes
looks good!

2022-10-01 20:17 UTC, merged